#!/usr/bin/env bash
#transfers file from client to server


if [ "$#" -lt 3 ];
then
    echo "Usage: ${0##*/} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path="$1"
ip="$2"
username="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path" "$username"@"$ip":~/
