#!/usr/bin/env bash

# Update and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Ensure that Nginx listens on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# HTML content
echo "Hello World!" |sudo tee /var/www/html/index.html > /dev/null

#reload Nginx
sudo service nginx restart
