#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using the while loop + IFS

while IFS=':' read -r username _ userid groupid _ homedir shell; do
    passcode=$(awk -F':' -v user="$username" '$1 == user {print $2}' /etc/shadow)
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $username"
done < /etc/passwd
