#!/usr/bin/env bash
# Bash script to configure an Ubuntu server with the below requirements.

cp /etc/hosts /etc/hosts.new

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
